### ISSUE TITLE
Printing test names in async mode

### ISSUE THREAD

**Issue by TrevorBurnham** [masylum/testosterone#1]
So, the docs state that

> The spec will be printed when done function is called

But  `spec` is ignored when `sync` is `false` (the default), right? Here's a simple test case in CoffeeScript:

```
testosterone = require('testosterone') title: 'suite name'
{assert} = testosterone

testosterone
  .add 'test name', ->
    assert.equal 1, 1
```

This just gives the output

```
suite name
```

and a green checkmark.

I guess I can work with that by creating a new `testosterone` instance for each set of assertions I want to give a name to. Is that the best possible approach? (I realize that the async nature of the tests makes printing their output very tricky.)

**Comment by masylum** [comment]
I need to write a better documentation... :)

Basically, the problem testing asynchronous code is that you _don't know_ when your asserts are all done. Having a `done` function in your tests `add('test name', function (done) {` tells _testosterone_ when all your asserts are done and ready to print 'test name'.

Your case is easier! Your code is synchronous, so you don't need to tell _testosterone_ when your asserts are done. So you just need to set `sync` to `true`.

Here you can see some examples using `sync` to `true`.
https://github.com/masylum/dialect/tree/master/test

To be honest, I recommend you to stub any asynchronous code, as it usually involves I/O. It will make your tests faster and without side effects.

**Comment by masylum** [comment]
I rewrote some parts of the documentation and the tests. I hope it helps.

**Comment by TrevorBurnham** [comment]
Thanks, I was actually doing some async testing (sorry, the example I distilled it to for this issue is a bit misleading). I notice that `testosterone.png` shows some great-looking output in conjunction with `GET`/`POST`... but the docs don't contain the code that generated that output. Any way get output in that style with my own async stuff, or is it only possible with Testosterone's built-in HTTP calls?

**Comment by masylum** [comment]
I have a mini parser that highlights the words [given / then / and / when] because they are common to write specs on https://github.com/aslakhellesoy/cucumber/wiki/gherkin

I also highlight things in between backticks.

You can see an async example here:

https://github.com/masylum/testosterone/blob/master/tests/serial.js
